server:
  port: 8080
  error:
    path: /error
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true
    session:
      timeout: 30m
  tomcat:
    basedir: ./tomcat
    accesslog:
      buffered: true
      directory:  ./logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      prefix: access_log
      rename-on-rotate: false
      pattern: common
      request-attributes-enabled: false
      rotate: true
      max-days: 60
    threads:
      max: 500
    uri-encoding: utf-8
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
logging:
  config: classpath:log4j2-dev.xml
proj:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
swagger:
  enable: true